version: '2.1'

services:

  web:
    build: .
    command: "python3 manage.py runserver 0.0.0.0:8011"
    volumes:
      - ./app:/usr/src/app
      - ./scripts:/scripts
    ports:
      - "8011:8011"
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    env_file:
     - app/postgres.env
    volumes:
     - ./database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "ping", "-c","1", "localhost:8012"]
      interval: 3s
      timeout: 5s
      retries: 3
    image: postgres:alpine